# Generated by Django 2.2.6 on 2020-07-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20200628_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя друга')),
                ('books', models.ManyToManyField(blank=True, related_name='books', to='p_library.Book')),
            ],
        ),
    ]
