# Generated by Django 2.2.6 on 2020-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_delete_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя друга')),
                ('books', models.ManyToManyField(blank=True, related_name='books', to='p_library.Book', verbose_name='Книги')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
