# Generated by Django 2.2.6 on 2020-07-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='friend_reader',
            field=models.ManyToManyField(blank=True, related_name='book_reader', to='p_library.Friend', verbose_name='Читающие друзья'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='book_covers'),
        ),
    ]
